"""
inp_writer.py
-------------
Generates CalculiX .inp from FEAModel (typed) or legacy dict.
Units: SI (m, Pa, N, N·m).

CalculiX face numbering for C3D4 / C3D10 (0-based face index → S-label):
  Face 0 (S1): corner nodes [0,1,2]
  Face 1 (S2): corner nodes [0,1,3]
  Face 2 (S3): corner nodes [1,2,3]
  Face 3 (S4): corner nodes [0,2,3]
"""

from __future__ import annotations
import math
import numpy as np
from typing import Any
from .models import (
    FEAModel, MeshData, MaterialModel,
    BoundaryCondition, BcType,
    Load, LoadType, LocalizedLoadData, DirectionMode,
    Node, FaceGroup,
)

# face_idx (0-based) → CalculiX surface label
_FACE_LABEL = {0: "S1", 1: "S2", 2: "S3", 3: "S4"}
# face_idx (0-based) → CalculiX pressure dload label
_PRESS_LABEL = {0: "P1", 1: "P2", 2: "P3", 3: "P4"}
# Maximum node IDs per line (CalculiX allows 16 data items per continuation line)
_NODES_PER_LINE = 16


class InpWriterV2:
    """Typed writer — takes FEAModel dataclass."""

    def __init__(self, model: FEAModel):
        self.model = model
        self.mesh = model.mesh
        self.mesh.build_lookups()

    def write(self, path: str) -> None:
        self._validate_before_write()
        lines: list[str] = []
        self._heading(lines)
        self._nodes(lines)
        self._elements(lines)
        self._node_sets_for_bcs(lines)     # NSET definitions before *STEP
        self._surface_definitions(lines)   # *SURFACE for pressure (optional) + ELSETs
        self._material(lines)
        self._step(lines)
        # CalculiX parses INP as ASCII; a stray non-ASCII byte (em-dash,
        # smart quote, unicode in a user label) crashes ccx with exit 201.
        text = ("\n".join(lines) + "\n").encode("ascii", "replace").decode("ascii")
        with open(path, "w", encoding="ascii", newline="\n") as f:
            f.write(text)

    def _validate_before_write(self) -> None:
        """Pre-write validation: ensure every BC/load has valid mesh entities."""
        import logging
        log = logging.getLogger(__name__)
        errors: list[str] = []

        for i, bc in enumerate(self.model.boundary_conditions):
            nids = bc.node_ids
            if not nids:
                try:
                    nids = self.mesh.face(bc.face_id).node_ids
                except KeyError:
                    nids = []
            if not nids:
                errors.append(
                    f"BC #{i+1} ({bc.type.value}) on face {bc.face_id}: "
                    f"no nodes resolved — NSET would be empty.")

        for i, load in enumerate(self.model.loads):
            if load.type in (LoadType.PRESSURE, LoadType.SURFACE_TRACTION,
                             LoadType.DISTRIBUTED_FORCE):
                try:
                    fg = self.mesh.face(load.face_id)
                except KeyError:
                    errors.append(
                        f"Load #{i+1} ({load.type.value}) on face {load.face_id}: "
                        f"face not found in mesh.")
                    continue
                if not fg.element_faces:
                    errors.append(
                        f"Load #{i+1} ({load.type.value}) on face {load.face_id}: "
                        f"no element-faces — DLOAD would be empty.")
            elif load.type == LoadType.POINT_LOAD:
                if load.localized is None or load.localized.resolved_node_id is None:
                    errors.append(
                        f"Load #{i+1} (PointLoad) on face {load.face_id}: "
                        f"no resolved node ID.")

        if errors:
            msg = "INP validation failed:\n" + "\n".join(f"  • {e}" for e in errors)
            log.error(msg)
            raise ValueError(msg)

    # Tet face corner indices (for area computation): face_idx → 3 corner indices
    # in the element.nodes array. C3D10 first 4 entries are the tet corners.
    _FACE_CORNERS = {
        0: (0, 1, 2),
        1: (0, 1, 3),
        2: (1, 2, 3),
        3: (0, 2, 3),
    }
    # C3D10 mid-side node indices on each face (Abaqus/CCX numbering:
    # n4=mid(0-1), n5=mid(1-2), n6=mid(2-0), n7=mid(0-3), n8=mid(1-3), n9=mid(2-3)).
    _FACE_MIDSIDES = {
        0: (4, 5, 6),   # face 0 corners (0,1,2) → edges 4,5,6
        1: (4, 8, 7),   # face 1 corners (0,1,3) → edges 4,8,7
        2: (5, 9, 8),   # face 2 corners (1,2,3) → edges 5,9,8
        3: (6, 9, 7),   # face 3 corners (0,2,3) → edges 6,9,7
    }

    # ── Model definition section ──────────────────────────────────────────────

    def _heading(self, lines: list[str]) -> None:
        lines += [
            "*HEADING",
            "FEA Solver - Linear Static Analysis",
            "** Generated by FEASolver.App",
            "",
        ]

    def _nodes(self, lines: list[str]) -> None:
        lines.append("*NODE, NSET=NALL")
        for n in self.mesh.nodes:
            lines.append(f"{n.id}, {n.x:.10e}, {n.y:.10e}, {n.z:.10e}")
        lines.append("")

    def _elements(self, lines: list[str]) -> None:
        by_type: dict[str, list] = {}
        for e in self.mesh.elements:
            by_type.setdefault(e.type, []).append(e)
        for etype, elems in by_type.items():
            lines.append(f"*ELEMENT, TYPE={etype}, ELSET=EALL")
            for e in elems:
                node_str = ", ".join(str(n) for n in e.nodes)
                lines.append(f"{e.id}, {node_str}")
        lines.append("")

    def _node_sets_for_bcs(self, lines: list[str]) -> None:
        """Define NSET for each BC before the step."""
        import logging
        log = logging.getLogger(__name__)
        for bc in self.model.boundary_conditions:
            nset = _bc_nset_name(bc)
            nids = bc.node_ids
            if not nids:
                try:
                    nids = self.mesh.face(bc.face_id).node_ids
                except KeyError:
                    nids = []
            if not nids:
                log.warning(f"BC {bc.type.value} face={bc.face_id}: empty NSET, skipping")
                continue
            log.info(f"NSET {nset}: {len(nids)} nodes from face {bc.face_id}")
            lines.append(f"*NSET, NSET={nset}")
            for i in range(0, len(nids), _NODES_PER_LINE):
                lines.append(", ".join(str(n) for n in nids[i:i + _NODES_PER_LINE]))
            lines.append("")

    def _surface_definitions(self, lines: list[str]) -> None:
        """Pre-define *SURFACE for any pressure/traction faces that need element sets."""
        import logging
        log = logging.getLogger(__name__)
        seen: set[int] = set()
        for load in self.model.loads:
            if load.type not in (LoadType.PRESSURE,):
                continue
            if load.face_id in seen:
                continue
            seen.add(load.face_id)
            try:
                fg = self.mesh.face(load.face_id)
            except KeyError:
                log.warning(f"Pressure face={load.face_id}: not in mesh, skipping SURFACE")
                continue
            if not fg.element_faces:
                log.warning(f"Pressure face={load.face_id}: no element-faces, skipping SURFACE")
                continue
            surf_name = _surf_name(load.face_id)
            lines.append(f"*SURFACE, NAME={surf_name}, TYPE=ELEMENT")
            count = 0
            for ef in fg.element_faces:
                if not isinstance(ef, (list, tuple)) or len(ef) < 2:
                    continue
                elem_id, face_idx = int(ef[0]), int(ef[1])
                lbl = _FACE_LABEL.get(face_idx)
                if lbl is None:
                    continue
                lines.append(f"{elem_id}, {lbl}")
                count += 1
            log.info(f"SURFACE {surf_name}: {count} element-faces from face {load.face_id}")
            lines.append("")

    def _material(self, lines: list[str]) -> None:
        m = self.model.material
        mat_name = m.name.upper().replace(" ", "_")
        lines += [
            f"*MATERIAL, NAME={mat_name}",
            "*ELASTIC",
            f"{m.youngs_modulus:.6e}, {m.poissons_ratio}",
            "",
            f"*SOLID SECTION, ELSET=EALL, MATERIAL={mat_name}",
            "1.0",
            "",
        ]

    # ── Step section ──────────────────────────────────────────────────────────

    def _step(self, lines: list[str]) -> None:
        lines += ["*STEP", "*STATIC", ""]

        self._write_bcs(lines)

        cload:  list[str] = []
        dload:  list[str] = []

        for load in self.model.loads:
            if load.type == LoadType.POINT_LOAD:
                self._write_point_load(load, cload)
            elif load.type in (LoadType.MOMENT, LoadType.TORQUE):
                self._write_moment(load, cload)
            elif load.type == LoadType.SURFACE_TRACTION:
                # CalculiX has no vector-traction keyword — convert to equivalent
                # nodal *CLOAD via face-area lumping (preserves total force).
                self._write_surface_traction(load, cload)
            elif load.type == LoadType.DISTRIBUTED_FORCE:
                self._write_distributed_force(load, cload)
            elif load.type == LoadType.PRESSURE:
                self._write_pressure(load, dload)

        if cload:
            lines.append("*CLOAD")
            lines.extend(cload)
            lines.append("")
        if dload:
            lines.append("*DLOAD")
            lines.extend(dload)
            lines.append("")

        # OUTPUT=3D forces ASCII .frd output even when CCX defaults to binary
        # on some Windows builds. RF in *NODE FILE writes nodal reaction forces
        # so we can verify Σ(reactions) ≈ -Σ(applied loads) post-solve.
        lines += [
            "*NODE PRINT, NSET=NALL", "U,RF", "",
            "*EL PRINT, ELSET=EALL", "S,E", "",
            "*NODE FILE, OUTPUT=3D", "U,RF", "",
            "*EL FILE, OUTPUT=3D", "S,E", "",
            "*END STEP",
        ]

    def _write_bcs(self, lines: list[str]) -> None:
        for bc in self.model.boundary_conditions:
            nset = _bc_nset_name(bc)
            nids = bc.node_ids
            if not nids:
                try:
                    nids = self.mesh.face(bc.face_id).node_ids
                except KeyError:
                    nids = []
            if not nids:
                continue
            dofs = bc.type.constrained_dofs()
            if not dofs:
                continue
            lines.append("*BOUNDARY")
            # Use range format when DOFs are consecutive (e.g. 1,3 for Fixed)
            if len(dofs) > 1 and (dofs[-1] - dofs[0]) == (len(dofs) - 1):
                lines.append(f"{nset}, {dofs[0]}, {dofs[-1]}")
            else:
                for dof in dofs:
                    lines.append(f"{nset}, {dof}, {dof}")
            lines.append("")

    def _write_surface_traction(self, load: Load, cload: list[str]) -> None:
        """
        Surface traction (Pa) in an arbitrary direction.

        CalculiX has no generic vector-traction keyword, so we convert the
        distributed traction to equivalent *CLOAD nodal forces using the
        CONSISTENT (Galerkin) lumping for the element type:
          • C3D4  (linear tet face = 3-node tri):  each corner gets area/3 × t
          • C3D10 (quadratic tet face = 6-node tri): corners get 0,
                  midsides get area/3 × t  (this is the analytically correct
                  lumping — uniform-distribution to all 6 nodes is WRONG and
                  introduces large local stress errors)

        Each element-face is lumped independently and contributions are
        accumulated, so adjacent faces sharing nodes sum correctly.

        Direction handling:
          • EXPLICIT       → use load.direction (unit vector) globally.
          • NORMAL_OUTWARD → compute outward normal per element-face (away
                             from 4th tet vertex). Correct for tilted/curved
                             surfaces without the user specifying a vector.
          • NORMAL_INWARD  → negated NORMAL_OUTWARD.
        Total applied force equals magnitude × Σ(area · direction_i).
        """
        try:
            fg = self.mesh.face(load.face_id)
        except KeyError:
            return
        if not fg.element_faces or not fg.node_ids:
            return

        explicit_d = np.array(load.direction or [0.0, 0.0, -1.0], dtype=float)
        norm_d = np.linalg.norm(explicit_d)
        explicit_d = (explicit_d / norm_d
                      if norm_d > 1e-12 else np.array([0.0, 0.0, -1.0]))

        # nid → [Fx, Fy, Fz] accumulator
        nodal_F: dict[int, np.ndarray] = {}

        for ef in fg.element_faces:
            if not isinstance(ef, (list, tuple)) or len(ef) < 2:
                continue
            elem_id, face_idx = int(ef[0]), int(ef[1])
            try:
                elem = self.mesh.element(elem_id)
            except KeyError:
                continue
            corners = self._FACE_CORNERS.get(face_idx)
            if corners is None:
                continue
            if any(ci >= len(elem.nodes) for ci in corners):
                continue
            try:
                nA = self.mesh.node(elem.nodes[corners[0]])
                nB = self.mesh.node(elem.nodes[corners[1]])
                nC = self.mesh.node(elem.nodes[corners[2]])
            except KeyError:
                continue
            pA = np.array([nA.x, nA.y, nA.z])
            pB = np.array([nB.x, nB.y, nB.z])
            pC = np.array([nC.x, nC.y, nC.z])
            cross_n = np.cross(pB - pA, pC - pA)
            area = 0.5 * float(np.linalg.norm(cross_n))
            if area <= 0.0:
                continue

            # Per-face direction (outward when NORMAL_*). We compare against the
            # 4th tet vertex: outward normal points AWAY from it. This is robust
            # even when face corner ordering is inconsistent across elements.
            if load.direction_mode is DirectionMode.EXPLICIT:
                direction = explicit_d
            else:
                n_hat = cross_n / (2.0 * area)
                other_idx = [i for i in range(4) if i not in corners][0]
                if other_idx < len(elem.nodes):
                    try:
                        n4 = self.mesh.node(elem.nodes[other_idx])
                        to_fourth = np.array([n4.x, n4.y, n4.z]) - pA
                        if float(np.dot(n_hat, to_fourth)) > 0.0:
                            n_hat = -n_hat
                    except KeyError:
                        pass
                if load.direction_mode is DirectionMode.NORMAL_INWARD:
                    n_hat = -n_hat
                direction = n_hat

            F_face = float(load.magnitude) * direction * area

            is_quadratic = (elem.type == "C3D10" and len(elem.nodes) >= 10)
            if is_quadratic:
                # Consistent 6-node-triangle lumping: corners=0, midsides=F/3
                mids = self._FACE_MIDSIDES.get(face_idx)
                if mids is None or any(mi >= len(elem.nodes) for mi in mids):
                    # Fall back to corner lumping if numbering is unexpected
                    targets = [elem.nodes[ci] for ci in corners]
                    per_node = F_face / 3.0
                else:
                    targets = [elem.nodes[mi] for mi in mids]
                    per_node = F_face / 3.0
            else:
                # Linear tet (C3D4) — each corner gets F/3
                targets = [elem.nodes[ci] for ci in corners]
                per_node = F_face / 3.0

            for nid in targets:
                nodal_F.setdefault(nid, np.zeros(3))
                nodal_F[nid] += per_node

        if not nodal_F:
            return

        # Stable output ordering for diff-friendly INP files
        for nid in sorted(nodal_F.keys()):
            F = nodal_F[nid]
            for dof, fv in enumerate(F, 1):
                if abs(fv) > 1e-15:
                    cload.append(f"{nid}, {dof}, {fv:.6e}")

    def _write_distributed_force(self, load: Load, cload: list[str]) -> None:
        """
        Total-force-on-face load (DistributedForce).

        User specifies F_total (N) via load.magnitude and direction (unit vec).
        We compute traction = (F_total / A_face) · dir and delegate to the
        surface-traction consistent-lumping path. Σ CLOAD on the face equals
        F_total · dir exactly, independent of mesh density.
        """
        try:
            fg = self.mesh.face(load.face_id)
        except KeyError:
            return
        if not fg.element_faces or not fg.node_ids:
            return
        if abs(load.magnitude) < 1e-15:
            return

        total_area = 0.0
        for ef in fg.element_faces:
            if not isinstance(ef, (list, tuple)) or len(ef) < 2:
                continue
            elem_id, face_idx = int(ef[0]), int(ef[1])
            try:
                elem = self.mesh.element(elem_id)
            except KeyError:
                continue
            corners = self._FACE_CORNERS.get(face_idx)
            if corners is None or any(ci >= len(elem.nodes) for ci in corners):
                continue
            try:
                nA = self.mesh.node(elem.nodes[corners[0]])
                nB = self.mesh.node(elem.nodes[corners[1]])
                nC = self.mesh.node(elem.nodes[corners[2]])
            except KeyError:
                continue
            pA = np.array([nA.x, nA.y, nA.z])
            pB = np.array([nB.x, nB.y, nB.z])
            pC = np.array([nC.x, nC.y, nC.z])
            total_area += 0.5 * float(np.linalg.norm(np.cross(pB - pA, pC - pA)))
        if total_area <= 1e-30:
            return

        # Build an equivalent SurfaceTraction and reuse its lumping. magnitude
        # here is already in Pa after division. direction_mode passes through
        # so NORMAL_OUTWARD on a tilted face stays normal per-facet.
        direction = load.direction or [0.0, 0.0, -1.0]
        traction_load = Load(
            type=LoadType.SURFACE_TRACTION,
            face_id=load.face_id,
            magnitude=float(load.magnitude) / total_area,
            direction=direction,
            localized=None,
            direction_mode=load.direction_mode,
        )
        self._write_surface_traction(traction_load, cload)

    def _write_pressure(self, load: Load, dload: list[str]) -> None:
        """
        Normal pressure on element faces via *DLOAD P1-P4.
        Positive magnitude = compression (inward normal).
        """
        try:
            fg = self.mesh.face(load.face_id)
        except KeyError:
            return
        if not fg.element_faces:
            return
        if abs(load.magnitude) < 1e-15:
            return
        for ef in fg.element_faces:
            if not isinstance(ef, (list, tuple)) or len(ef) < 2:
                continue
            elem_id, face_idx = int(ef[0]), int(ef[1])
            lbl = _PRESS_LABEL.get(face_idx)
            if lbl is None:
                continue
            dload.append(f"{elem_id}, {lbl}, {load.magnitude:.6e}")

    def _write_point_load(self, load: Load, cload: list[str]) -> None:
        loc = load.localized
        if loc is None:
            return
        force = loc.force or [0.0, 0.0, 0.0]
        if sum(abs(v) for v in force) < 1e-15:
            return  # no non-zero component — skip silently
        nid = loc.resolved_node_id
        if nid is None:
            target = tuple(loc.xyz) if loc.xyz else (0.0, 0.0, 0.0)
            try:
                fg = self.mesh.face(load.face_id)
            except KeyError:
                return
            if not fg.node_ids:
                return
            nearest = self.mesh.nearest_node_on_face(load.face_id, target)
            nid = nearest.id
        for dof, fv in enumerate(force, 1):
            if abs(fv) > 1e-15:
                cload.append(f"{nid}, {dof}, {fv:.6e}")

    def _write_moment(self, load: Load, cload: list[str]) -> None:
        loc = load.localized
        if loc is None:
            return
        axis = loc.axis_direction or [0.0, 1.0, 0.0]
        magnitude = loc.magnitude if loc.magnitude is not None else load.magnitude
        if magnitude is None or abs(magnitude) < 1e-15:
            return
        try:
            face_nodes = self.mesh.nodes_on_face(load.face_id)
        except KeyError:
            return
        if not face_nodes:
            return
        origin = loc.xyz if loc.xyz is not None else self._face_centroid(load.face_id)
        node_positions = {n.id: [n.x, n.y, n.z] for n in face_nodes}
        forces = torque_to_nodal_forces(node_positions, origin, axis, magnitude)
        for nid, f in forces.items():
            for dof, fv in enumerate(f, 1):
                if abs(fv) > 1e-15:
                    cload.append(f"{nid}, {dof}, {fv:.6e}")

    def _face_centroid(self, face_id: int) -> list[float]:
        nodes = self.mesh.nodes_on_face(face_id)
        if not nodes:
            return [0.0, 0.0, 0.0]
        return [
            sum(n.x for n in nodes) / len(nodes),
            sum(n.y for n in nodes) / len(nodes),
            sum(n.z for n in nodes) / len(nodes),
        ]


# ── Name helpers ──────────────────────────────────────────────────────────────

def _bc_nset_name(bc: "BoundaryCondition") -> str:
    return f"BC_F{bc.face_id}_{bc.type.value.upper()}"


def _surf_name(face_id: int) -> str:
    return f"SURF_F{face_id}"


# ── Legacy dict-based writer (backwards compat for tests) ────────────────────

class InpWriter:
    """Legacy dict-based writer — kept for backward compat."""

    def __init__(self, model: dict[str, Any]):
        self.model = model
        self.mesh = model["mesh"]
        self.material = model["material"]
        self.bcs = model.get("boundary_conditions", [])
        self.loads = model.get("loads", [])
        self.node_pos: dict[int, list[float]] = {
            n["id"]: [n["x"], n["y"], n["z"]] for n in self.mesh["nodes"]}
        self.face_nodes: dict[int, list[int]] = {
            f["face_id"]: f["node_ids"] for f in self.mesh["faces"]}

    def write(self, path: str) -> None:
        lines: list[str] = []
        self._heading(lines)
        self._nodes(lines)
        self._elements(lines)
        self._material(lines)
        self._step(lines)
        # CalculiX parses INP as ASCII; a stray non-ASCII byte (em-dash,
        # smart quote, unicode in a user label) crashes ccx with exit 201.
        text = ("\n".join(lines) + "\n").encode("ascii", "replace").decode("ascii")
        with open(path, "w", encoding="ascii", newline="\n") as f:
            f.write(text)

    def _heading(self, lines):
        lines += ["*HEADING", "FEA Solver - Linear Static Analysis", ""]

    def _nodes(self, lines):
        lines.append("*NODE, NSET=NALL")
        for n in self.mesh["nodes"]:
            lines.append(f"{n['id']}, {n['x']:.10e}, {n['y']:.10e}, {n['z']:.10e}")
        lines.append("")

    def _elements(self, lines):
        by_type: dict[str, list] = {}
        for e in self.mesh["elements"]:
            by_type.setdefault(e["type"], []).append(e)
        for etype, elems in by_type.items():
            lines.append(f"*ELEMENT, TYPE={etype}, ELSET=EALL")
            for e in elems:
                lines.append(f"{e['id']}, " + ", ".join(str(n) for n in e["nodes"]))
        lines.append("")

    def _material(self, lines):
        m = self.material
        lines += [
            f"*MATERIAL, NAME={m['name'].upper()}", "*ELASTIC",
            f"{m['youngs_modulus']:.6e}, {m['poissons_ratio']}", "",
            f"*SOLID SECTION, ELSET=EALL, MATERIAL={m['name'].upper()}", "1.0", "",
        ]

    def _step(self, lines):
        lines += ["*STEP", "*STATIC", ""]
        for bc in self.bcs:
            nset = f"BC_F{bc['face_id']}_{bc['type'].upper()}"
            nids = bc.get("node_ids") or self.face_nodes.get(bc["face_id"], [])
            if not nids:
                continue
            lines += [f"*NSET, NSET={nset}",
                      ", ".join(str(n) for n in nids[:_NODES_PER_LINE]), ""]
            bc_type = bc["type"].upper()
            if bc_type in ("FIXED", "PINNED"):
                lines += ["*BOUNDARY", f"{nset}, 1, 3", ""]
            elif bc_type == "ROLLERX":
                lines += ["*BOUNDARY", f"{nset}, 1, 1", ""]
            elif bc_type == "ROLLERY":
                lines += ["*BOUNDARY", f"{nset}, 2, 2", ""]
            elif bc_type == "ROLLERZ":
                lines += ["*BOUNDARY", f"{nset}, 3, 3", ""]
        cload: list[str] = []
        dload: list[str] = []
        for load in self.loads:
            lt = load["type"].upper()
            if lt == "PRESSURE":
                fg_ef = next((f["element_faces"] for f in self.mesh["faces"]
                              if f["face_id"] == load["face_id"]), [])
                for ef in fg_ef:
                    eid, fi = int(ef[0]), int(ef[1])
                    lbl = _PRESS_LABEL.get(fi, "P1")
                    dload.append(f"{eid}, {lbl}, {load.get('magnitude', 0):.6e}")
            elif lt in ("POINTLOAD", "POINT_LOAD"):
                loc = load.get("localized", {})
                nid = loc.get("resolved_node_id") or \
                      self._nearest(load["face_id"], loc.get("xyz"))
                if nid:
                    for dof, fv in enumerate(loc.get("force", [0, 0, 0]), 1):
                        if abs(fv) > 1e-15:
                            cload.append(f"{nid}, {dof}, {fv:.6e}")
        if cload:
            lines += ["*CLOAD"] + cload + [""]
        if dload:
            lines += ["*DLOAD"] + dload + [""]
        lines += [
            "*NODE PRINT, NSET=NALL", "U", "",
            "*EL PRINT, ELSET=EALL", "S,E", "",
            "*NODE FILE", "U", "",
            "*EL FILE", "S,E", "",
            "*END STEP",
        ]

    def _nearest(self, face_id, xyz):
        nids = self.face_nodes.get(face_id, [])
        if not nids:
            return None
        if not xyz:
            return nids[0]
        t = np.array(xyz)
        return min(nids, key=lambda n: np.linalg.norm(
            np.array(self.node_pos[n]) - t) if n in self.node_pos else math.inf)


# ── Torque utility (shared) ───────────────────────────────────────────────────

def torque_to_nodal_forces(
    node_positions: dict[int, list[float]],
    axis_origin: list[float],
    axis_direction: list[float],
    torque_Nm: float,
    validate: bool = True,
) -> dict[int, list[float]]:
    """Distribute torque T (N·m) about an axis into equivalent nodal forces.

    Uses the r²-weighted formula:
        F_i = (T / D) * (a × r_perp_i)
        where  r_perp_i = component of (pos_i – origin) perpendicular to axis
               D = Σ_j |r_perp_j|²

    This yields Σ_i r_perp_i × F_i = T·a exactly (analytically).

    Edge cases:
      • Nodes on the axis (r_perp ≈ 0) contribute 0 force and 0 to D.
      • If ALL nodes are on the axis (D ≈ 0), returns zero forces for all nodes.

    Raises ValueError if net moment deviates from T by more than 1e-6 relative
    (can be disabled with validate=False).
    """
    a = np.array(axis_direction, dtype=float)
    norm_a = np.linalg.norm(a)
    if norm_a < 1e-12:
        return {nid: [0.0, 0.0, 0.0] for nid in node_positions}
    a /= norm_a
    origin = np.array(axis_origin, dtype=float)

    # Compute radial (perpendicular-to-axis) vectors for every node
    r_perp: dict[int, np.ndarray] = {}
    for nid, pos in node_positions.items():
        r = np.array(pos, dtype=float) - origin
        rp = r - float(np.dot(r, a)) * a
        r_perp[nid] = rp

    D = float(sum(np.dot(rp, rp) for rp in r_perp.values()))

    if D < 1e-30:
        # All nodes are on (or within numerical noise of) the axis —
        # no moment arm available; fall back to zero forces and warn.
        import logging
        logging.getLogger(__name__).warning(
            "torque_to_nodal_forces: all nodes on axis (D≈0); "
            "torque cannot be applied — returning zero forces. "
            "Consider using Remote Moment mode or selecting a different axis."
        )
        return {nid: [0.0, 0.0, 0.0] for nid in node_positions}

    # F_i = (T/D) * (a × r_perp_i)
    forces: dict[int, list[float]] = {}
    for nid, rp in r_perp.items():
        forces[nid] = (torque_Nm / D * np.cross(a, rp)).tolist()

    if validate and abs(torque_Nm) > 1e-15:
        # Verify Σ r_perp_i × F_i projected onto axis = T
        m_net = np.zeros(3)
        for nid, f in forces.items():
            m_net += np.cross(r_perp[nid], np.array(f))
        m_axial = float(np.dot(m_net, a))
        err = abs(m_axial - torque_Nm) / abs(torque_Nm)
        if err > 1e-6:
            raise ValueError(
                f"Torque distribution validation failed: "
                f"M_net={m_axial:.6e} N·m, requested={torque_Nm:.6e} N·m, "
                f"relative error={err:.2e} (threshold 1e-6). "
                f"D={D:.6e}, nodes={len(node_positions)}"
            )

    return forces
